In [6]:
from itertools import product
from cftime import DatetimeNoLeap

import xarray as xr
import numpy as np

In [7]:
dates = [
    DatetimeNoLeap(year, month, 1)
    for year, month in product(range(1, 3), range(1, 13))
]

da = xr.DataArray(np.arange(24), coords=[dates], dims=["time"], name="foo")


In [10]:
dates = xr.cftime_range(start="0001", periods=24, freq="MS", calendar="noleap")
da = xr.DataArray(np.arange(24), coords=[dates], dims=["time"], name="foo")


C:\Users\esthe\AppData\Local\Temp\ipykernel_30708\1749591175.py:1: FutureWarning: cftime_range() is deprecated, please use xarray.date_range(..., use_cftime=True) instead.
  dates = xr.cftime_range(start="0001", periods=24, freq="MS", calendar="noleap")


In [11]:
xr.infer_freq(dates)


'MS'

In [12]:
dates.strftime("%c")


Index(['Tue Jan  1 00:00:00 0001', 'Fri Feb  1 00:00:00 0001',
       'Fri Mar  1 00:00:00 0001', 'Mon Apr  1 00:00:00 0001',
       'Wed May  1 00:00:00 0001', 'Sat Jun  1 00:00:00 0001',
       'Mon Jul  1 00:00:00 0001', 'Thu Aug  1 00:00:00 0001',
       'Sun Sep  1 00:00:00 0001', 'Tue Oct  1 00:00:00 0001',
       'Fri Nov  1 00:00:00 0001', 'Sun Dec  1 00:00:00 0001',
       'Wed Jan  1 00:00:00 0002', 'Sat Feb  1 00:00:00 0002',
       'Sat Mar  1 00:00:00 0002', 'Tue Apr  1 00:00:00 0002',
       'Thu May  1 00:00:00 0002', 'Sun Jun  1 00:00:00 0002',
       'Tue Jul  1 00:00:00 0002', 'Fri Aug  1 00:00:00 0002',
       'Mon Sep  1 00:00:00 0002', 'Wed Oct  1 00:00:00 0002',
       'Sat Nov  1 00:00:00 0002', 'Mon Dec  1 00:00:00 0002'],
      dtype='str')

In [13]:
da["time"].dt.strftime("%Y%m%d")


<xarray.DataArray 'strftime' (time: 24)> Size: 192B
array(['00010101', '00010201', '00010301', '00010401', '00010501',
       '00010601', '00010701', '00010801', '00010901', '00011001',
       '00011101', '00011201', '00020101', '00020201', '00020301',
       '00020401', '00020501', '00020601', '00020701', '00020801',
       '00020901', '00021001', '00021101', '00021201'], dtype=object)
Coordinates:
  * time     (time) object 192B 0001-01-01 00:00:00 ... 0002-12-01 00:00:00

In [15]:
dates = xr.date_range(start="2001", periods=24, freq="MS", calendar="noleap", use_cftime=True)
da_nl = xr.DataArray(np.arange(24), coords=[dates], dims=["time"], name="foo")
da_std = da.convert_calendar("standard", use_cftime=True)


In [16]:
da.time.dt.year


<xarray.DataArray 'year' (time: 24)> Size: 192B
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])
Coordinates:
  * time     (time) object 192B 0001-01-01 00:00:00 ... 0002-12-01 00:00:00

In [17]:
da.time.dt.month


<xarray.DataArray 'month' (time: 24)> Size: 192B
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12])
Coordinates:
  * time     (time) object 192B 0001-01-01 00:00:00 ... 0002-12-01 00:00:00

In [18]:
da.time.dt.season


<xarray.DataArray 'season' (time: 24)> Size: 288B
array(['DJF', 'DJF', 'MAM', 'MAM', 'MAM', 'JJA', 'JJA', 'JJA', 'SON',
       'SON', 'SON', 'DJF', 'DJF', 'DJF', 'MAM', 'MAM', 'MAM', 'JJA',
       'JJA', 'JJA', 'SON', 'SON', 'SON', 'DJF'], dtype='<U3')
Coordinates:
  * time     (time) object 192B 0001-01-01 00:00:00 ... 0002-12-01 00:00:00

In [19]:
da.time.dt.dayofyear


<xarray.DataArray 'dayofyear' (time: 24)> Size: 192B
array([  1,  32,  60,  91, 121, 152, 182, 213, 244, 274, 305, 335,   1,
        32,  60,  91, 121, 152, 182, 213, 244, 274, 305, 335])
Coordinates:
  * time     (time) object 192B 0001-01-01 00:00:00 ... 0002-12-01 00:00:00

In [20]:
da.time.dt.days_in_month


<xarray.DataArray 'days_in_month' (time: 24)> Size: 192B
array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31, 30, 31,
       30, 31, 31, 30, 31, 30, 31])
Coordinates:
  * time     (time) object 192B 0001-01-01 00:00:00 ... 0002-12-01 00:00:00

In [21]:
da.to_netcdf("example-no-leap.nc")


In [23]:
reopened = xr.open_dataset("example-no-leap.nc")
reopened


<xarray.Dataset> Size: 384B
Dimensions:  (time: 24)
Coordinates:
  * time     (time) object 192B 0001-01-01 00:00:00 ... 0002-12-01 00:00:00
Data variables:
    foo      (time) int64 192B ...

In [26]:
import pandas as pd

da = xr.DataArray(
    np.random.rand(3, 4),
    coords={
        "time": pd.date_range("2025-01-01", periods=3),
        "x": [10, 20, 30, 40]
    },
    dims=["time", "x"]
)

In [27]:
da


<xarray.DataArray (time: 3, x: 4)> Size: 96B
array([[0.94032229, 0.4618077 , 0.28027232, 0.47704483],
       [0.3188377 , 0.41144078, 0.87594456, 0.71203533],
       [0.59336176, 0.29447102, 0.81550264, 0.16640826]])
Coordinates:
  * time     (time) datetime64[us] 24B 2025-01-01 2025-01-02 2025-01-03
  * x        (x) int64 32B 10 20 30 40

In [31]:
da.sel(time="2025-01-01")

<xarray.DataArray (x: 4)> Size: 32B
array([0.94032229, 0.4618077 , 0.28027232, 0.47704483])
Coordinates:
  * x        (x) int64 32B 10 20 30 40
    time     datetime64[us] 8B 2025-01-01

In [32]:
da.isel(x=[2,3])

<xarray.DataArray (time: 3, x: 2)> Size: 48B
array([[0.28027232, 0.47704483],
       [0.87594456, 0.71203533],
       [0.81550264, 0.16640826]])
Coordinates:
  * time     (time) datetime64[us] 24B 2025-01-01 2025-01-02 2025-01-03
  * x        (x) int64 16B 30 40